export const productsBackup = [{
  name: "BOSCH (S40 240) (D23) Asia 60Ah 540A R+",
  image_url: "",
  voltage: 600,
  capacity_ah: 50,
  cycle_life: 2,
  weight_kg: "20",
  warranty_years: "1",
  dimensions: "(100, 50, 60)",
  price: 3160.01,
  in_stock: false,
  starting_current_a: 400,
  polarity: "R+",
  production_country: "Ukraine",
  brand: "Bosch",
  terminal_category: "AGM",
  terminal_cover_type: "DIN",
}, {
  name: "MAXION Premium 110Аh 1000A R+ (L5)",
  image_url: "https://akbcenter.com.ua/image/cache/catalog/maxionpremium/60067042199.1-800x800.jpg",
  voltage: 1000,
  capacity_ah: 110,
  cycle_life: 2,
  weight_kg: "20",
  warranty_years: "2",
  dimensions: "(80, 60, 20)",
  price: 3631.7,
  in_stock: true,
  starting_current_a: 110,
  polarity: "L+",
  production_country: "Ukraine",
  brand: "maxion",
  terminal_category: "GEL",
  terminal_cover_type: "JIS",
  }];
